os: linux
language: minimal
jdk: oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9-base
      - libstdc++6
before_install:
  - chmod +x .travis/*
install:
  - .travis/install.sh
script:
  - .travis/script.sh
after_success:
  - .travis/send.sh success $WEBHOOK_URL
after_failure:
  - .travis/send.sh failure $WEBHOOK_URL
deploy:
  - provider: releases
    api_key: "$GITHUB_API_KEY"
    file_glob: true
    file: build/release/*.tar.gz
    skip_cleanup: true
    prerelease: true
    on:
      tags: true
      branch: master


